### ISSUE TITLE
Room Joining Endpoint

### ISSUE THREAD

**Issue by xanthehammer** [xanthehammer/FilmFlock#2]
Create an endpoint to join a room.

### Request Format
POST
roomId: string
username: string

### Acceptance Criteria
* If the requested room has not been created and thus does not exist a `400` error code should be returned.
* If the `username` already exists in the room a `400` error code should be returned.
* If the room exists and the `username` has not already been added to the room then a `200` code should be returned along with a unique ID to uniquely identify the user.

https://app.swaggerhub.com/apis/BARROSMYLES/FilmFlock/1.0.0#/

**Comment by mylesbarros** [comment]
https://app.swaggerhub.com/apis/BARROSMYLES/FilmFlock/1.0.0#/

**Comment by mylesbarros** [comment]
PR opened
