### ISSUE TITLE
Add Film Endpoint

### ISSUE THREAD

**Issue by xanthehammer** [xanthehammer/FilmFlock#3]
Create an endpoint to add (suggest) a film for the movie night in a given room.

### Request Format
POST
roomId: string
userId: string
films: [string]

### Acceptance Criteria
* If the provided roomId does not identify an existing room the endpoint should return a `400` error code.
* If the userId does not identify a user in the room the endpoint should return a `400` error code.
* If the provided film array is empty then the endpoint should return a `400` error code. This includes the subsequent requirement such that if the array contains only empty strings it should also be rejected.
* If any of the films in the provided array are an empty string they should be accepted but the empty film title should be excluded.
* If any of the films in the provided array already exist in the room (case-insensitive title comparison) then they should be ignored but the endpoint should not return an error code.
* Each of the film titles not rejected by the above criteria should be added to the room and given a unique ID. A `200` status code should be returned.

https://app.swaggerhub.com/apis/BARROSMYLES/FilmFlock/1.0.0#/

**Comment by mylesbarros** [comment]
https://app.swaggerhub.com/apis/BARROSMYLES/FilmFlock/1.0.0#/
