### ISSUE TITLE
SelectMethod Endpoint

### ISSUE THREAD

**Issue by xanthehammer** [xanthehammer/FilmFlock#5]
Create an endpoint for selecting a resolution type for a given room.

### Request Format
POST
roomId: string
methodId: integer
adminId: string

### Acceptance Criteria
* If the provided roomId does not match an existing roomId it should be rejected.
* If the provided adminId does not match the adminId of the room the request should be rejected with a `403` status code.
* If the provided methodId does not match a supported methodId it should be rejected with a `400` status code.
* If the request passes the above requirements then a `200` status code should be returned and we should record which method the room will use to select a film.

https://app.swaggerhub.com/apis/BARROSMYLES/FilmFlock/1.0.0#/

**Comment by mylesbarros** [comment]
https://app.swaggerhub.com/apis/BARROSMYLES/FilmFlock/1.0.0#/

**Comment by mylesbarros** [comment]
No longer needed
